version: "3.8"

services:
  slurm:
    image: ghcr.io/itkovian/rocky8-slurm:main
    hostname: slurmctl
    container_name: slurmctl
    stdin_open: true
    tty: true
    working_dir: /pyslurm
    environment:
      PYTHON: "3.9"
    volumes:
      - ${RUNNER_WORKSPACE}/pyslurm:/pyslurm
